use super::*;
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

mod class_gen;
pub(crate) mod gen_choice;
pub(crate) mod gen_newtype;
pub(crate) mod gen_struct;
pub mod helpers;
pub mod native_gen;
pub(crate) mod test_choice;
mod test_gen;
pub(crate) mod test_newtype;
pub(crate) mod test_struct;
pub mod type_map;

/// Default Java class name prefix
const DEFAULT_PREFIX: &str = "Asn";

pub struct JavaConfig {
    pub prefix: String,
    pub default_enc: String,
    pub package: String,
    pub out_dir: PathBuf,
}

impl Default for JavaConfig {
    fn default() -> Self {
        Self {
            prefix: DEFAULT_PREFIX.to_string(),
            default_enc: "ber".to_string(),
            package: String::new(),
            out_dir: PathBuf::from("java/src"),
        }
    }
}

/// Entry point: generate Java classes from parsed types
pub fn generate(
    types: &[TypeInfo],
    cfg: &JavaConfig,
    asn_defs: &HashMap<String, String>,
    named_consts: &HashMap<String, Vec<(String, i32)>>,
) {
    let project_root = &cfg.out_dir;

    // —— Compute Maven directory layout —————————————————
    let pkg_path = helpers::package_to_path(&cfg.package);
    let main_dir = project_root.join("src/main/java").join(&pkg_path);
    let test_dir = project_root.join("src/test/java").join(&pkg_path);
    let res_dir = project_root.join("src/main/resources");

    fs::create_dir_all(&main_dir).expect("failed to create main source dir");
    fs::create_dir_all(&test_dir).expect("failed to create test source dir");
    fs::create_dir_all(&res_dir).expect("failed to create resources dir");

    // —— Java source files ——————————————————————————
    for t in types {
        let code = class_gen::gen_class(
            t,
            types,
            &cfg.prefix,
            &cfg.default_enc,
            &cfg.package,
            asn_defs,
            named_consts,
        );
        fs::write(
            main_dir.join(format!("{}{}.java", cfg.prefix, t.name)),
            &code,
        )
        .unwrap();

        let test_code = test_gen::gen_test_class(t, types, &cfg.prefix, &cfg.package, asn_defs);
        fs::write(
            test_dir.join(format!("{}{}Test.java", cfg.prefix, t.name)),
            &test_code,
        )
        .unwrap();
    }

    // Native + Base
    fs::write(
        main_dir.join(format!("{}Native.java", cfg.prefix)),
        &native_gen::gen_native(&cfg.prefix, &cfg.package),
    )
    .unwrap();
    fs::write(
        main_dir.join(format!("{}Base.java", cfg.prefix)),
        &native_gen::gen_base(&cfg.prefix, &cfg.package, &cfg.default_enc),
    )
    .unwrap();

    // —— DefaultInner* wrappers for built-in ASN.1 types —————————
    // Data lives only in _v (no Lombok `value` field, no Lombok @Data):
    // getters/setters must not shadow InnerBase.getValue()/setValue().
    let defaults: &[(&str, &str, &str)] = &[
        ("DefaultInnerVisibleString", "String", "\"x\""),
        ("DefaultInnerUtf8String", "String", "\"x\""),
        ("DefaultInnerOctetString", "byte[]", "new byte[]{ 1 }"),
    ];
    for (name, jtype, init) in defaults {
        let (body, ctor_param) = match *jtype {
            "byte[]" => {
                let body = format!(
                    r#"    @JsonValue
    public Object toJsonValue() {{ Object v = _v.get("_"); if (v instanceof byte[]) return InnerBase.hex((byte[]) v); return v != null ? v : ""; }}
    @SuppressWarnings("unchecked")
    @JsonCreator
    public static {name} fromJson(Object v) {{
        if (v instanceof java.util.Map) {{
            Object hex = ((java.util.Map<String, Object>) v).get("value");
            if (hex instanceof String) return new {name}(InnerBase.unhex((String) hex));
            return new {name}();
        }}
        return new {name}(v instanceof String ? InnerBase.unhex((String) v) : new byte[0]);
    }}"#,
                    name = name
                );
                (body, "byte[] value".to_string())
            }
            _ => {
                let body = format!(
                    r#"    @JsonValue
    public Object toJsonValue() {{ return _v.get("_"); }}
    @SuppressWarnings("unchecked")
    @JsonCreator
    public static {name} fromJson(Object v) {{
        if (v instanceof java.util.Map) {{
            Object s = ((java.util.Map<String, Object>) v).get("value");
            return new {name}(s instanceof String ? (String) s : "x");
        }}
        return new {name}(v instanceof String ? (String) v : "x");
    }}"#,
                    name = name
                );
                (body, "String value".to_string())
            }
        };
        let code = format!(
            r#"// Auto-generated by csasn1 v{} — built-in ASN.1 type wrapper

package {pkg};

import com.fasterxml.jackson.annotation.*;

public class {name} extends InnerBase {{
    public {name}() {{ _v.put("_", {init}); }}
    public {name}({ctor_param}) {{ _v.put("_", value); }}
    {body}
    public byte[] encode() {{ throw new UnsupportedOperationException("{name} has no standalone ASN.1 definition"); }}
    public static {name} decode(byte[] data) {{ return new {name}(); }}
}}
"#,
            env!("CARGO_PKG_VERSION"),
            pkg = cfg.package,
            name = name,
            init = init,
            ctor_param = ctor_param,
            body = body,
        );
        fs::write(main_dir.join(format!("{}.java", name)), &code).unwrap();
    }

    // InnerEmpty — special case (no value field, just a placeholder)
    let empty_code = format!(
        r#"// Auto-generated by csasn1 v{} — InnerEmpty placeholder

package {pkg};

public class InnerEmpty extends InnerBase {{
    public byte[] encode() {{ throw new UnsupportedOperationException("InnerEmpty has no ASN.1 definition"); }}
    public static InnerEmpty decode(byte[] data) {{ return new InnerEmpty(); }}
}}
"#,
        env!("CARGO_PKG_VERSION"),
        pkg = cfg.package,
    );
    fs::write(main_dir.join("InnerEmpty.java"), &empty_code).unwrap();

    // V — semantic helpers for the _v unified data store
    fs::write(main_dir.join("V.java"), &native_gen::gen_v(&cfg.package)).unwrap();

    // —— Maven pom.xml ———————————————————————————————
    let pom_path = project_root.join("pom.xml");
    if !pom_path.exists() {
        fs::write(&pom_path, &gen_pom(&cfg.prefix, &cfg.package)).expect("failed to write pom.xml");
        println!("  wrote pom.xml");
    }

    // —— Copy DLL to resources ——————————————————————
    if let Ok(exe_path) = std::env::current_exe() {
        if let Some(exe_dir) = exe_path.parent() {
            let dll_name = if cfg!(target_os = "windows") {
                "asn1.dll"
            } else {
                "libasn1.so"
            };
            let dll_src = exe_dir.join(dll_name);
            if dll_src.exists() {
                fs::copy(&dll_src, res_dir.join(dll_name))
                    .expect("failed to copy asn1.dll to resources");
                let jna_plat_dir = res_dir.join("win32-x86-64");
                fs::create_dir_all(&jna_plat_dir).ok();
                fs::copy(&dll_src, jna_plat_dir.join(dll_name))
                    .expect("failed to copy asn1.dll to resources/win32-x86-64/");
                println!("  copied {} to resources/ (incl. win32-x86-64)", dll_name);
            }
        }
    }

    println!(
        "✓ generated {} Java classes (incl. {}Native.java, {}Base.java) in {:?}",
        types.len(),
        cfg.prefix,
        cfg.prefix,
        main_dir
    );
    println!(
        "✓ generated {} Java test classes in {:?}",
        types.len(),
        test_dir
    );
}

/// Generate a standalone Maven pom.xml for the auto-generated data types.
fn gen_pom(prefix: &str, package: &str) -> String {
    let group_id = package
        .rsplit_once('.')
        .map(|(head, _)| head.to_string())
        .unwrap_or_else(|| "com.example".to_string());
    let artifact_id = format!("{}-data", prefix.to_lowercase());
    include_str!("templates/pom.xml.txt")
        .replace("__GROUP_ID__", &group_id)
        .replace("__ARTIFACT_ID__", &artifact_id)
        .to_string()
}
