/// Generate CmsNative.java — JNA bridge to the Rust asn1.dll.
pub fn gen_native(prefix: &str, package: &str) -> String {
    let pkg = if package.is_empty() {
        String::new()
    } else {
        format!("package {};\n\n", package)
    };
    let ver = super::helpers::gen_version();
    format!(
        r#"// Auto-generated by {ver}: {pfx}Native (JNA bridge)
// All native functions return JSON strings; binary data is base64-encoded.

{pkg}import com.sun.jna.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Map;

public class {pfx}Native {{
    private static final NativeImpl LIB = Native.load("asn1", NativeImpl.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private interface NativeImpl extends Library {{
        Pointer csasn1_ping();
        Pointer csasn1_encode(String typeName, String encoding, String json);
        Pointer csasn1_decode(String typeName, String encoding, byte[] data, int len);
        void csasn1_free_string(Pointer s);
    }}

    /** Quick check that native library loads and responds. */
    public static String ping() {{
        Pointer p = LIB.csasn1_ping();
        try {{
            return p.getString(0, "UTF-8");
        }} finally {{
            LIB.csasn1_free_string(p);
        }}
    }}

    /** Read a null-terminated C string from a Pointer and free it. */
    private static String readAndFree(Pointer p) {{
        try {{
            return p.getString(0, "UTF-8");
        }} finally {{
            LIB.csasn1_free_string(p);
        }}
    }}

    /**
     * Encode JSON to ASN.1 binary.
     * @param typeName  ASN.1 type name
     * @param encoding  encoding rule ("ber", "der", "aper", "uper")
     * @param json      JSON representation of the data
     * @return encoded binary data
     */
    public static byte[] encode(String typeName, String encoding, String json) {{
        try {{
            String resp = readAndFree(LIB.csasn1_encode(typeName, encoding, json));
            @SuppressWarnings("unchecked")
            Map<String, Object> m = MAPPER.readValue(resp, Map.class);
            if (Boolean.TRUE.equals(m.get("ok"))) {{
                return MAPPER.convertValue(m.get("bytes"), byte[].class);
            }}
            throw new RuntimeException("encode failed: " + m.get("error"));
        }} catch (Exception e) {{
            throw new RuntimeException(e);
        }}
    }}

    /**
     * Decode ASN.1 binary to JSON.
     * @param typeName  ASN.1 type name
     * @param encoding  encoding rule
     * @param data      binary encoded data
     * @return JSON representation
     */
    public static String decode(String typeName, String encoding, byte[] data) {{
        try {{
            String resp = readAndFree(LIB.csasn1_decode(typeName, encoding, data, data.length));
            @SuppressWarnings("unchecked")
            Map<String, Object> m = MAPPER.readValue(resp, Map.class);
            if (Boolean.TRUE.equals(m.get("ok"))) {{
                return MAPPER.writeValueAsString(m.get("value"));
            }}
            throw new RuntimeException("decode failed: " + m.get("error"));
        }} catch (Exception e) {{
            throw new RuntimeException(e);
        }}
    }}
}}"#,
        pkg = pkg,
        pfx = prefix,
        ver = ver,
    )
}

/// Generate CmsBase.java — abstract base class for all data types.
pub fn gen_base(prefix: &str, package: &str, default_enc: &str) -> String {
    let pkg = if package.is_empty() {
        String::new()
    } else {
        format!("package {};\n\n", package)
    };
    let ver = super::helpers::gen_version();
    format!(
        r#"// Auto-generated by {ver}: {pfx}Base (abstract base class)

{pkg}import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.module.SimpleModule;
import java.io.IOException;

public abstract class {pfx}Base {{
    public static final String DEFAULT_ENCODING = "{enc}";

    /** Convert byte array to lowercase hex string. */
    public static String hex(byte[] bytes) {{
        if (bytes == null) return "";
        StringBuilder sb = new StringBuilder(bytes.length * 2);
        for (byte b : bytes) {{
            sb.append(String.format("%02x", b & 0xFF));
        }}
        return sb.toString();
    }}

    /** Convert hex string to byte array. */
    public static byte[] unhex(String hex) {{
        if (hex == null || hex.isEmpty()) return new byte[0];
        int len = hex.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {{
            data[i / 2] = (byte) ((Character.digit(hex.charAt(i), 16) << 4)
                                 + Character.digit(hex.charAt(i + 1), 16));
        }}
        return data;
    }}

    @Override
    public String toString() {{
        try {{
            return new ObjectMapper().writeValueAsString(this);
        }} catch (Exception e) {{
            return getClass().getSimpleName() + "{{...}}";
        }}
    }}

    /** Create an ObjectMapper configured for JER-compatible serialization. */
    protected static ObjectMapper createMapper() {{
        ObjectMapper m = new ObjectMapper();
        m.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        m.setVisibility(PropertyAccessor.GETTER, JsonAutoDetect.Visibility.NONE);
        m.setVisibility(PropertyAccessor.IS_GETTER, JsonAutoDetect.Visibility.NONE);
        m.setVisibility(PropertyAccessor.SETTER, JsonAutoDetect.Visibility.NONE);
        m.setVisibility(PropertyAccessor.CREATOR, JsonAutoDetect.Visibility.NONE);
        SimpleModule mod = new SimpleModule();
        mod.addSerializer(byte[].class, new JsonSerializer<byte[]>() {{
            @Override
            public void serialize(byte[] value, JsonGenerator gen, SerializerProvider prov) throws IOException {{
                gen.writeString(hex(value));
            }}
        }});
        mod.addDeserializer(byte[].class, new JsonDeserializer<byte[]>() {{
            @Override
            public byte[] deserialize(JsonParser p, DeserializationContext ctx) throws IOException {{
                return unhex(p.getValueAsString());
            }}
        }});
        m.registerModule(mod);
        return m;
    }}

    /** Convert integer value to BIT STRING JER hex (MSB-first byte packing). */
    public static String bitStringHex(int value, int numBits) {{
        int bytes = (numBits + 7) / 8;
        int result = 0;
        for (int i = 0; i < numBits; i++) {{
            if ((value & (1 << i)) != 0) {{
                int bytePos = i / 8;
                int bitPos = 7 - (i % 8);
                result |= (1 << (bytePos * 8 + bitPos));
            }}
        }}
        return String.format("%0" + (bytes * 2) + "x", result);
    }}

    /** Parse BIT STRING JER hex back to integer value. */
    public static int parseBitStringHex(String hex, int numBits) {{
        int bytes = Integer.parseInt(hex, 16);
        int result = 0;
        for (int i = 0; i < numBits; i++) {{
            int bytePos = i / 8;
            int bitPos = 7 - (i % 8);
            if ((bytes & (1 << (bytePos * 8 + bitPos))) != 0) {{
                result |= (1 << i);
            }}
        }}
        return result;
    }}
}}
"#,
        pkg = pkg,
        pfx = prefix,
        enc = default_enc,
        ver = ver,
    )
}
