/// Generate CmsNative.java — JNA bridge to the Rust asn1.dll.
pub fn gen_native(prefix: &str, package: &str) -> String {
    let pkg = if package.is_empty() {
        String::new()
    } else {
        format!("package {};\n\n", package)
    };
    let ver = super::helpers::gen_version();
    format!(
        r#"// Auto-generated by {ver}: {pfx}Native (JNA bridge)
// All native functions return JSON strings; binary data is base64-encoded.

{pkg}import com.sun.jna.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Map;

public class {pfx}Native {{
    private static final NativeImpl LIB = Native.load("asn1", NativeImpl.class,
        java.util.Collections.singletonMap(Library.OPTION_STRING_ENCODING, "UTF-8"));
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private interface NativeImpl extends Library {{
        Pointer csasn1_ping();
        Pointer csasn1_encode(String typeName, String encoding, String json);
        Pointer csasn1_decode(String typeName, String encoding, byte[] data, int len);
        void csasn1_free_string(Pointer s);
    }}

    /** Quick check that native library loads and responds. */
    public static String ping() {{
        Pointer p = LIB.csasn1_ping();
        try {{
            return p.getString(0, "UTF-8");
        }} finally {{
            LIB.csasn1_free_string(p);
        }}
    }}

    /** Read a null-terminated C string from a Pointer and free it. */
    private static String readAndFree(Pointer p) {{
        try {{
            return p.getString(0, "UTF-8");
        }} finally {{
            LIB.csasn1_free_string(p);
        }}
    }}

    /**
     * Encode JSON to ASN.1 binary.
     * @param typeName  ASN.1 type name
     * @param encoding  encoding rule ("ber", "der", "aper", "uper")
     * @param json      JSON representation of the data
     * @return encoded binary data
     */
    public static byte[] encode(String typeName, String encoding, String json) {{
        try {{
            String resp = readAndFree(LIB.csasn1_encode(typeName, encoding, json));
            @SuppressWarnings("unchecked")
            Map<String, Object> m = MAPPER.readValue(resp, Map.class);
            if (Boolean.TRUE.equals(m.get("ok"))) {{
                return MAPPER.convertValue(m.get("bytes"), byte[].class);
            }}
            throw new RuntimeException("encode failed: " + m.get("error"));
        }} catch (Exception e) {{
            throw new RuntimeException(e);
        }}
    }}

    /**
     * Decode ASN.1 binary to JSON.
     * @param typeName  ASN.1 type name
     * @param encoding  encoding rule
     * @param data      binary encoded data
     * @return JSON representation (with 0x prefixes stripped from hex strings)
     */
    public static String decode(String typeName, String encoding, byte[] data) {{
        try {{
            String resp = readAndFree(LIB.csasn1_decode(typeName, encoding, data, data.length));
            @SuppressWarnings("unchecked")
            Map<String, Object> m = MAPPER.readValue(resp, Map.class);
            if (Boolean.TRUE.equals(m.get("ok"))) {{
                String json = MAPPER.writeValueAsString(m.get("value"));
                // Strip 0x prefixes from hex strings (rasn JER uses {{:02X?}} format)
                json = json.replace("0x", "").replace("0X", "");
                return json;
            }}
            throw new RuntimeException("decode failed: " + m.get("error"));
        }} catch (Exception e) {{
            throw new RuntimeException(e);
        }}
    }}
}}"#,
        pkg = pkg,
        pfx = prefix,
        ver = ver,
    )
}

/// Generate CmsBase.java — abstract base class for all data types.
pub fn gen_base(prefix: &str, package: &str, default_enc: &str) -> String {
    let pkg = if package.is_empty() {
        String::new()
    } else {
        format!("package {};\n\n", package)
    };
    let ver = super::helpers::gen_version();
    format!(
        r#"// Auto-generated by {ver}: {pfx}Base (abstract base class)

{pkg}import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.module.SimpleModule;
import java.io.IOException;

public abstract class {pfx}Base {{
    public static final String DEFAULT_ENCODING = "{enc}";

    /** The unified data store: all scalar/SEQUENCE/CHOICE fields live here. Underscore prefix avoids conflict with ASN.1 field names. */
    @JsonIgnore
    public java.util.LinkedHashMap<String, Object> _v = new java.util.LinkedHashMap<>();

    /** Encode this type to APER bytes via Rust FFI. Implemented by each generated subclass. */
    public abstract byte[] encode();

    /** Decode APER bytes into a new instance of this type. */
    public static {pfx}Base decode(byte[] data) {{ throw new UnsupportedOperationException("Use concrete subclass decode()"); }}

    /** Convert byte array to lowercase hex string. */
    public static String hex(byte[] bytes) {{
        if (bytes == null) return "";
        StringBuilder sb = new StringBuilder(bytes.length * 2);
        for (byte b : bytes) {{
            sb.append(String.format("%02x", b & 0xFF));
        }}
        return sb.toString();
    }}

    /** Convert hex string to byte array. Handles both "4048F5C3" and "0x400x48..." formats. */
    public static byte[] unhex(String hex) {{
        if (hex == null || hex.isEmpty()) return new byte[0];
        // Strip 0x prefixes (rasn JER uses {{:02X?}} format which emits "0x40" per byte)
        hex = hex.replace("0x", "").replace("0X", "");
        int len = hex.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {{
            data[i / 2] = (byte) ((Character.digit(hex.charAt(i), 16) << 4)
                                 + Character.digit(hex.charAt(i + 1), 16));
        }}
        return data;
    }}

    @Override
    public String toString() {{
        try {{
            return new ObjectMapper().writeValueAsString(this);
        }} catch (Exception e) {{
            return getClass().getSimpleName() + "{{...}}";
        }}
    }}

    /** Create an ObjectMapper configured for JER-compatible serialization. */
    protected static ObjectMapper createMapper() {{
        ObjectMapper m = new ObjectMapper();
        m.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        m.setVisibility(PropertyAccessor.GETTER, JsonAutoDetect.Visibility.NONE);
        m.setVisibility(PropertyAccessor.IS_GETTER, JsonAutoDetect.Visibility.NONE);
        m.setVisibility(PropertyAccessor.SETTER, JsonAutoDetect.Visibility.NONE);
        m.setVisibility(PropertyAccessor.CREATOR, JsonAutoDetect.Visibility.NONE);
        SimpleModule mod = new SimpleModule();
        mod.addSerializer(byte[].class, new JsonSerializer<byte[]>() {{
            @Override
            public void serialize(byte[] value, JsonGenerator gen, SerializerProvider prov) throws IOException {{
                gen.writeString(hex(value));
            }}
        }});
        mod.addDeserializer(byte[].class, new JsonDeserializer<byte[]>() {{
            @Override
            public byte[] deserialize(JsonParser p, DeserializationContext ctx) throws IOException {{
                return unhex(p.getValueAsString());
            }}
        }});
        m.registerModule(mod);
        return m;
    }}

    /** Convert integer value to BIT STRING JER hex (MSB-first byte packing). */
    public static String bitStringHex(int value, int numBits) {{
        int bytes = (numBits + 7) / 8;
        int result = 0;
        for (int i = 0; i < numBits; i++) {{
            if ((value & (1 << i)) != 0) {{
                int bytePos = i / 8;
                int bitPos = 7 - (i % 8);
                result |= (1 << (bytePos * 8 + bitPos));
            }}
        }}
        // Output bytes LSB-first — matches Rust JER byte ordering
        StringBuilder sb = new StringBuilder();
        for (int j = 0; j < bytes; j++) {{
            sb.append(String.format("%02x", (result >> (j * 8)) & 0xFF));
        }}
        return sb.toString();
    }}

    /** Parse BIT STRING JER hex back to integer value. */
    public static int parseBitStringHex(String hex, int numBits) {{
        int bytes = hex.length() / 2;
        // Parse LSB-first hex bytes back to integer
        int packed = 0;
        for (int b = 0; b < bytes; b++) {{
            int byteVal = Integer.parseInt(hex.substring(b * 2, b * 2 + 2), 16);
            packed |= (byteVal << (b * 8));
        }}
        // Convert from MSB-first byte packing to LSB-0 packed value
        int result = 0;
        for (int i = 0; i < numBits; i++) {{
            int bytePos = i / 8;
            int bitPos = 7 - (i % 8);
            if ((packed & (1 << (bytePos * 8 + bitPos))) != 0) {{
                result |= (1 << i);
            }}
        }}
        return result;
    }}

    /**
     * Unified serialization via _v map:
     * - Scalars: _v has only "_" → returns the scalar value directly
     * - CHOICE: _v has "_choice" → returns {{"variant": value}}
     * - SEQUENCE: all fields in _v → returns recursively processed map
     */
    @JsonValue
    public Object toJsonValue() {{
        if (_v.containsKey("_choice")) {{
            String choice = (String) _v.get("_choice");
            java.util.LinkedHashMap<String, Object> out = new java.util.LinkedHashMap<>();
            if (choice != null && _v.containsKey(choice)) {{
                out.put(choice, toJson(_v.get(choice)));
            }}
            return out;
        }}
        if (_v.size() == 1 && _v.containsKey("_")) {{
            return toJson(_v.get("_"));
        }}
        // Recursively process _v content to unwrap nested scalar wrappers {{"_": value}}.
        // This handles the case where _v stores raw Maps like {{"_": 0}} (from InnerInt32U()._v).
        return toJson(_v);
    }}

    /** Return the scalar value stored under {{@code _}}. */
    @JsonIgnore
    public Object getValue() {{ return _v.get("_"); }}

    /** Set the scalar value under {{@code _}}. */
    public void setValue(Object v) {{ _v.put("_", v); }}

    /**
     * Recursively flatten _v content for correct JSON encoding:
     * - InnerBase instances -> their toJsonValue()
     * - Maps with only "_" (scalar wrappers) -> the scalar value
     * - Other Maps/Lists -> recursively processed
     * - Primitives -> as-is
     */
    public static Object toJson(Object val) {{
        if (val instanceof InnerBase) {{
            // Recursively process toJsonValue() result so that Map branch strips _-prefixed keys
            return toJson(((InnerBase) val).toJsonValue());
        }}
        if (val instanceof java.util.Map) {{
            java.util.Map<String, Object> m = (java.util.Map<String, Object>) val;
            // CHOICE map: {{"_choice": "variant", "variant": value}} -> {{"variant": value}}
            if (m.containsKey("_choice")) {{
                String choice = (String) m.get("_choice");
                java.util.LinkedHashMap<String, Object> out = new java.util.LinkedHashMap<>();
                if (choice != null && m.containsKey(choice)) {{
                    out.put(choice, toJson(m.get(choice)));
                }}
                return out;
            }}
            // Scalar wrapper: {{"_": value}} -> value
            if (m.size() == 1 && m.containsKey("_")) {{
                return toJson(m.get("_"));
            }}
            // Regular map — recursively process values, skip nulls and metadata
            java.util.LinkedHashMap<String, Object> result = new java.util.LinkedHashMap<>();
            for (java.util.Map.Entry<String, Object> e : m.entrySet()) {{
                if (e.getKey().startsWith("_")) continue;
                Object v = toJson(e.getValue());
                if (v != null) {{
                    result.put(e.getKey(), v);
                }}
            }}
            return result;
        }}
        if (val instanceof java.util.List) {{
            java.util.List<Object> list = (java.util.List<Object>) val;
            java.util.ArrayList<Object> result = new java.util.ArrayList<>();
            for (Object item : list) {{
                result.add(toJson(item));
            }}
            return result;
        }}
        return val;
    }}
}}
"#,
        pkg = pkg,
        pfx = prefix,
        enc = default_enc,
        ver = ver,
    )
}
