use super::super::*;

/// Re-use the version helper from the Java generator
pub fn gen_header_comment() -> String {
    format!("# Auto-generated by {}\n", super::super::java::helpers::gen_version())
}

/// Python-safe field name (avoid keywords)
pub fn py_safe_name(name: &str) -> String {
    let keywords = ["and", "as", "assert", "async", "await", "break", "class", "continue", "def",
        "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
        "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
        "while", "with", "yield", "True", "False", "None"];
    if keywords.contains(&name) {
        format!("{}_", name)
    } else {
        name.to_string()
    }
}

/// Default Python value for a type
pub fn py_default(jt: &str) -> &'static str {
    match jt {
        "int" => "0",
        "float" => "0.0",
        "bool" => "False",
        "str" => "\"\"",
        "bytes" => "b\"\"",
        _ => "None",
    }
}

/// Resolve a Rust type to Python type string
pub fn resolve_py_type(rust_type: &str, all: &[TypeInfo], prefix: &str) -> String {
    let rt = rust_type.trim();
    if rt.starts_with("Option <") {
        let inner = rt.trim_start_matches("Option <").trim_end_matches('>').trim();
        return resolve_py_type(inner, all, prefix);
    }
    if rt == "bool" || rt == "BOOLEAN" { return "bool".into(); }
    if rt == "i8" || rt == "i16" || rt == "i32" || rt == "i64" { return "int".into(); }
    if rt == "u8" || rt == "u16" || rt == "u32" || rt == "u64" { return "int".into(); }
    if rt == "f32" || rt == "f64" { return "float".into(); }
    if rt == "BIT_STRING" || rt.starts_with("BitString") || rt.starts_with("FixedBitString") { return "int".into(); }
    if rt == "OctetString" || rt.starts_with("FixedOctetString") { return "bytes".into(); }
    if rt.starts_with("VisibleString") || rt.starts_with("UTF8String") || rt == "String" { return "str".into(); }
    if rt.starts_with("Vec <") || rt.starts_with("SequenceOf <") { return "list".into(); }
    if rt.starts_with(prefix) || all.iter().any(|t| format!("{}{}", prefix, t.name) == rt || t.name == rt) {
        if rt.starts_with(prefix) { return rt.to_string(); }
        return format!("{}{}", prefix, rt);
    }
    "Any".into()
}

/// Generate Python field declaration
pub fn gen_field(f: &FieldInfo, all: &[TypeInfo], prefix: &str) -> String {
    let raw = f.identifier.as_deref().unwrap_or(&f.name);
    let name = py_safe_name(raw);
    let py_type = resolve_py_type(&f.rust_type, all, prefix);
    if f.is_list {
        format!("    {}: {} = field(default_factory=list)", name, py_type)
    } else if f.optional {
        format!("    {}: {} = None", name, py_type)
    } else {
        let default = py_default(&py_type);
        if default == "None" && py_type != "Any" {
            // Use lambda to handle forward references
            format!("    {}: {} = field(default_factory=lambda: {}())", name, py_type, py_type)
        } else if py_type == "bytes" && !f.is_list {
            // Fixed-length OCTET STRING — use correct-length default if fixed size
            let fixed = f.size_attr_raw.as_deref()
                .and_then(|raw| {
                    // Check if it's SIZE(N), not SIZE(M..N)
                    let no_range = !raw.contains("..");
                    if !no_range { return None; }
                    let digits: String = raw.chars().filter(|c| c.is_ascii_digit()).collect();
                    digits.parse::<usize>().ok()
                })
                .or_else(|| {
                    // Also check FixedOctetString rust_type
                    if f.rust_type.starts_with("FixedOctetString") {
                        let d: String = f.rust_type.chars().filter(|c| c.is_ascii_digit()).collect();
                        d.parse::<usize>().ok()
                    } else { None }
                })
                .unwrap_or(0);
            if fixed > 0 {
                format!("    {}: {} = b\"\\x00\" * {}", name, py_type, fixed)
            } else {
                format!("    {}: {} = {}", name, py_type, default)
            }
        } else {
            format!("    {}: {} = {}", name, py_type, default)
        }
    }
}
