use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use super::*;

/// Re-use the version helper from the Java generator
fn gen_header_comment() -> String {
    format!("# Auto-generated by {}\n", super::java::helpers::gen_version())
}

pub struct PythonConfig {
    pub prefix: String,
    pub package: String,
    pub default_enc: String,
    pub out_dir: PathBuf,
}

/// Python-safe field name (avoid keywords)
fn py_safe_name(name: &str) -> String {
    let keywords = ["and", "as", "assert", "async", "await", "break", "class", "continue", "def",
        "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
        "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
        "while", "with", "yield", "True", "False", "None"];
    if keywords.contains(&name) {
        format!("{}_", name)
    } else {
        name.to_string()
    }
}

/// Default Python value for a type
fn py_default(jt: &str, is_list: bool) -> &'static str {
    if is_list { return ""; }  // handled by gen_field via field(default_factory=list)
    match jt {
        "int" => "0",
        "float" => "0.0",
        "bool" => "False",
        "str" => "\"\"",
        "bytes" => "b\"\"",
        _ => "None",
    }
}

/// Resolve a Rust type to Python type string
fn resolve_py_type(rust_type: &str, all: &[TypeInfo], prefix: &str) -> String {
    let rt = rust_type.trim();
    if rt.starts_with("Option <") {
        let inner = rt.trim_start_matches("Option <").trim_end_matches('>').trim();
        return resolve_py_type(inner, all, prefix);
    }
    if rt == "bool" || rt == "BOOLEAN" { return "bool".into(); }
    if rt == "i8" || rt == "i16" || rt == "i32" || rt == "i64" { return "int".into(); }
    if rt == "u8" || rt == "u16" || rt == "u32" || rt == "u64" { return "int".into(); }
    if rt == "f32" || rt == "f64" { return "float".into(); }
    if rt == "BIT_STRING" || rt == "OctetString" || rt.starts_with("FixedOctetString") { return "bytes".into(); }
    if rt.starts_with("VisibleString") || rt.starts_with("UTF8String") || rt == "String" { return "str".into(); }
    if rt.starts_with("Vec <") || rt.starts_with("SequenceOf <") { return "list".into(); }
    if rt.starts_with(prefix) || all.iter().any(|t| format!("{}{}", prefix, t.name) == rt || t.name == rt) {
        if rt.starts_with(prefix) { return rt.to_string(); }
        return format!("{}{}", prefix, rt);
    }
    "Any".into()
}

/// Generate Python type for a FieldInfo
fn gen_field(f: &FieldInfo, all: &[TypeInfo], prefix: &str) -> String {
    let raw = f.identifier.as_deref().unwrap_or(&f.name);
    let name = py_safe_name(raw);
    let py_type = resolve_py_type(&f.rust_type, all, prefix);
    if f.is_list {
        format!("    {}: {} = field(default_factory=list)", name, py_type)
    } else {
        let default = py_default(&py_type, false);
        format!("    {}: {} = {}", name, py_type, default)
    }
}

/// Generate a complete Python class for each ASN.1 type
fn gen_type_class(ti: &TypeInfo, all: &[TypeInfo], prefix: &str, _package: &str, _cfg: &PythonConfig,
                  asn_defs: &HashMap<String, String>) -> String {
    let cn = format!("{}{}", prefix, ti.name);
    let mut c = String::new();

    // Docstring from ASN.1 definition (inside the class)
    c.push_str(&format!("@dataclass\n"));
    c.push_str(&format!("class {}:\n", cn));
    if let Some(def) = asn_defs.get(&ti.name) {
        c.push_str("    \"\"\"\n");
        c.push_str("    ```asn1\n");
        for line in def.lines() {
            c.push_str(&format!("    {}\n", line));
        }
        c.push_str("    ```\n");
        c.push_str("    \"\"\"\n");
    }

    match &ti.kind {
        TypeKind::Newtype { inner_type } => {
            let py_type = resolve_py_type(inner_type, all, prefix);
            let default = py_default(&py_type, false);
            c.push_str(&format!("    value: {} = {}\n", py_type, default));
        }
        TypeKind::Struct { fields } => {
            let has_optional = fields.iter().any(|f| f.optional);
            for f in fields {
                c.push_str(&gen_field(f, all, prefix));
                c.push('\n');
            }
            if has_optional {
                c.push_str("    _set: set[str] = field(default_factory=set, repr=False, compare=False)\n");
            }
        }
        TypeKind::Choice { variants } => {
            c.push_str("    _choice: str = \"\"\n");
            for v in variants {
                let name = py_safe_name(&v.name);
                let py_type = resolve_py_type(&v.inner_type, all, prefix);
                c.push_str(&format!("    {}: {} = None\n", name, py_type));
            }
        }
    }

    // Encode method
    c.push_str("\n    def encode(self) -> bytes:\n");
    c.push_str(&format!("        return encode(to_json(self), \"{}\")\n", ti.name));

    // Encode test method
    c.push_str("\n    def encode_test(self) -> bytes:\n");
    c.push_str(&format!("        return encode(to_json(self), \"{}\")\n", ti.name));

    // Decode classmethod
    c.push_str(&format!("\n    @classmethod\n"));
    c.push_str(&format!("    def decode(cls, data: bytes) -> \"{cn}\":\n"));
    c.push_str(&format!("        return from_json(decode_raw(data, \"{}\"), cls)\n", ti.name));

    c
}

/// Generate the _native.py bridge module
fn gen_native(prefix: &str, package: &str, default_enc: &str) -> String {
    let _pkg_dir = if package.is_empty() { prefix.to_lowercase() } else { package.replace('.', "_") };
    let mut c = String::new();
    c.push_str(&gen_header_comment());
    c.push_str("# ctypes bridge to native asn1.dll\n\n");
    c.push_str("import ctypes\n");
    c.push_str("import json\n");
    c.push_str("import os\n");
    c.push_str("import sys\n\n");

    c.push_str("_lib = None\n\n");
    c.push_str("def _load_lib():\n");
    c.push_str("    global _lib\n");
    c.push_str("    if _lib is not None:\n");
    c.push_str("        return _lib\n");
    c.push_str("    # Search for asn1.dll / libasn1.so\n");
    c.push_str("    dll_name = \"asn1.dll\" if sys.platform == \"win32\" else \"libasn1.so\"\n");
    c.push_str("    search_paths = [\n");
    c.push_str("        os.path.dirname(__file__),\n");
    c.push_str("        os.path.join(os.path.dirname(__file__), \"resources\"),\n");
    c.push_str("        os.path.join(os.path.dirname(__file__), \"..\", \"resources\"),\n");
    c.push_str("    ]\n");
    c.push_str("    for p in search_paths:\n");
    c.push_str("        full = os.path.join(p, dll_name)\n");
    c.push_str("        if os.path.exists(full):\n");
    c.push_str("            _lib = ctypes.cdll.LoadLibrary(full)\n");
    c.push_str("            _lib.csasn1_encode.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_char_p]\n");
    c.push_str("            _lib.csasn1_encode.restype = ctypes.c_void_p\n");
    c.push_str("            _lib.csasn1_decode.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.POINTER(ctypes.c_ubyte), ctypes.c_int]\n");
    c.push_str("            _lib.csasn1_decode.restype = ctypes.c_void_p\n");
    c.push_str("            _lib.csasn1_free_string.argtypes = [ctypes.c_void_p]\n");
    c.push_str("            _lib.csasn1_free_string.restype = None\n");
    c.push_str("            return _lib\n");
    c.push_str("    raise RuntimeError(f\"Cannot find {dll_name}\")\n\n");

    c.push_str("def _read_and_free(ptr) -> str:\n");
    c.push_str("    try:\n");
    c.push_str("        return ctypes.cast(ptr, ctypes.c_char_p).value.decode(\"utf-8\")\n");
    c.push_str("    finally:\n");
    c.push_str("        _load_lib().csasn1_free_string(ptr)\n\n");

    c.push_str(&format!("_ENCODING = \"{}\"\n\n", default_enc));

    c.push_str("def encode(json_str: str, type_name: str | None = None) -> bytes:\n");
    c.push_str("    lib = _load_lib()\n");
    c.push_str("    tn = (type_name or \"UNKNOWN\").encode()\n");
    c.push_str("    enc = _ENCODING.encode()\n");
    c.push_str("    js = json_str.encode()\n");
    c.push_str("    resp = _read_and_free(lib.csasn1_encode(tn, enc, js))\n");
    c.push_str("    result = json.loads(resp)\n");
    c.push_str("    if result.get(\"ok\"):\n");
    c.push_str("        return bytes(result[\"bytes\"])\n");
    c.push_str("    raise RuntimeError(f\"encode failed: {result.get('error')}\")\n\n");

    c.push_str("def decode_raw(data: bytes, type_name: str | None = None) -> str:\n");
    c.push_str("    lib = _load_lib()\n");
    c.push_str("    tn = (type_name or \"UNKNOWN\").encode()\n");
    c.push_str("    enc = _ENCODING.encode()\n");
    c.push_str("    buf = (ctypes.c_ubyte * len(data)).from_buffer_copy(data)\n");
    c.push_str("    resp = _read_and_free(lib.csasn1_decode(tn, enc, buf, len(data)))\n");
    c.push_str("    result = json.loads(resp)\n");
    c.push_str("    if result.get(\"ok\"):\n");
    c.push_str("        return json.dumps(result[\"value\"])\n");
    c.push_str("    raise RuntimeError(f\"decode failed: {result.get('error')}\")\n");

    c
}

/// Generate the _base.py module
fn gen_base(prefix: &str, package: &str) -> String {
    let _pkg_dir = if package.is_empty() { prefix.to_lowercase() } else { package.replace('.', "_") };
    let mut c = String::new();
    c.push_str(&gen_header_comment());
    c.push_str("# Base utilities for generated ASN.1 types\n\n");
    c.push_str("import json\n");
    c.push_str("from dataclasses import dataclass, field, asdict\n");
    c.push_str("from typing import Any\n\n");
    c.push_str("from ._native import encode, decode_raw\n\n");

    c.push_str("def to_json(obj) -> str:\n");
    c.push_str("    \"\"\"Serialize a dataclass instance to JSON for native encoding.\"\"\"\n");
    c.push_str("    return json.dumps(_to_dict(obj))\n\n");

    c.push_str("def _to_dict(obj) -> Any:\n");
    c.push_str("    if obj is None:\n");
    c.push_str("        return None\n");
    c.push_str("    if hasattr(obj, '_set'):\n");
    c.push_str("        d = {}\n");
    c.push_str("        for k, v in obj.__dict__.items():\n");
    c.push_str("            if k == '_set':\n");
    c.push_str("                continue\n");
    c.push_str("            d[k] = _to_dict(v)\n");
    c.push_str("        return d\n");
    c.push_str("    if hasattr(obj, '__dataclass_fields__'):\n");
    c.push_str("        return {k: _to_dict(v) for k, v in asdict(obj).items()}\n");
    c.push_str("    if isinstance(obj, bytes):\n");
    c.push_str("        return obj.hex()\n");
    c.push_str("    if isinstance(obj, list):\n");
    c.push_str("        return [_to_dict(x) for x in obj]\n");
    c.push_str("    return obj\n\n");

    c.push_str("def from_json(json_str: str, cls) -> Any:\n");
    c.push_str("    \"\"\"Deserialize JSON to a dataclass instance.\"\"\"\n");
    c.push_str("    data = json.loads(json_str)\n");
    c.push_str("    return _from_dict(data, cls)\n\n");

    c.push_str("def _from_dict(data: dict, cls) -> Any:\n");
    c.push_str("    if data is None:\n");
    c.push_str("        return None\n");
    c.push_str("    if hasattr(cls, '__dataclass_fields__'):\n");
    c.push_str("        fields = cls.__dataclass_fields__\n");
    c.push_str("        kwargs = {}\n");
    c.push_str("        for name, field_type in fields.items():\n");
    c.push_str("            if name == '_set':\n");
    c.push_str("                continue\n");
    c.push_str("            if name in data:\n");
    c.push_str("                kwargs[name] = _from_dict(data[name], field_type.type)\n");
    c.push_str("        return cls(**kwargs)\n");
    c.push_str("    if isinstance(data, list):\n");
    c.push_str("        # Try to determine element type\n");
    c.push_str("        return data\n");
    c.push_str("    return data\n");

    c
}

/// Generate __init__.py
fn gen_init(prefix: &str, package: &str) -> String {
    let _pkg = if package.is_empty() { prefix.to_lowercase() } else { package.replace('.', "_") };
    let mut c = String::new();
    c.push_str(&gen_header_comment());
    c.push_str("\n");
    c.push_str("from ._native import encode, decode_raw\n");
    c.push_str("from ._base import to_json, from_json\n");
    c.push_str("\n__all__ = []\n");
    c
}

/// Generate pixi.toml
fn gen_pixi_toml(prefix: &str, package: &str) -> String {
    let pkg_name = if package.is_empty() {
        format!("{}-data", prefix.to_lowercase())
    } else {
        package.to_string()
    };
    format!(r#"[project]
name = "{pkg_name}"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]

[tasks.test]
cmd = "pytest -v tests"
env = {{ PYTHONPATH = "src" }}

[dependencies]
python = ">=3.11"
pytest = ">=8"
pytest-xdist = "*"
"#)
}

/// Generate test function for a single type
fn gen_test(ti: &TypeInfo, all: &[TypeInfo], prefix: &str, _package: &str) -> String {
    let cn = format!("{}{}", prefix, ti.name);
    let mut c = String::new();
    c.push_str(&format!("class Test{cn}:\n"));
    c.push_str("    def test_encode_decode(self):\n");
    c.push_str(&format!("        obj = {cn}()\n"));

    match &ti.kind {
        TypeKind::Newtype { inner_type } => {
            let py_type = resolve_py_type(inner_type, all, prefix);
            match py_type.as_str() {
                "int" => c.push_str("        obj.value = 1\n"),
                "str" => c.push_str("        obj.value = \"test\"\n"),
                "bytes" => c.push_str("        obj.value = b\"\\x00\"\n"),
                _ => {}
            }
        }
        TypeKind::Struct { fields } => {
            for f in fields {
                let raw = f.identifier.as_deref().unwrap_or(&f.name);
                let name = py_safe_name(raw);
                let py_type = resolve_py_type(&f.rust_type, all, prefix);
                match py_type.as_str() {
                    "int" => c.push_str(&format!("        obj.{} = 1\n", name)),
                    "str" => c.push_str(&format!("        obj.{} = \"test\"\n", name)),
                    "bytes" => c.push_str(&format!("        obj.{} = b\"\\x01\"\n", name)),
                    "list" => c.push_str(&format!("        obj.{} = []\n", name)),
                    _ => {
                        if all.iter().any(|t| format!("{}{}", prefix, t.name) == py_type) {
                            c.push_str(&format!("        obj.{} = {}()\n", name, py_type));
                        }
                    }
                }
            }
        }
        TypeKind::Choice { .. } => {}
    }

    c.push_str("        data = obj.encode_test()\n");
    c.push_str(&format!("        decoded = {cn}.decode(data)\n"));
    c.push_str("        assert obj == decoded\n");
    c
}

/// Entry point: generate all Python files
pub fn generate(types: &[TypeInfo], cfg: &PythonConfig, asn_defs: &HashMap<String, String>,
                _named_consts: &HashMap<String, Vec<(String, i32)>>) {
    let project_root = &cfg.out_dir;

    let src_dir = project_root.join("src").join("cms_data");
    let test_dir = project_root.join("tests");

    fs::create_dir_all(&src_dir).expect("failed to create src dir");
    fs::create_dir_all(&test_dir).expect("failed to create test dir");

    // _native.py
    fs::write(src_dir.join("_native.py"), &gen_native(&cfg.prefix, &cfg.package, &cfg.default_enc))
        .expect("failed to write _native.py");

    // _base.py
    fs::write(src_dir.join("_base.py"), &gen_base(&cfg.prefix, &cfg.package))
        .expect("failed to write _base.py");

    // __init__.py (initial, updated later with type exports)
    fs::write(src_dir.join("__init__.py"), &gen_init(&cfg.prefix, &cfg.package))
        .expect("failed to write __init__.py");

    // pixi.toml — 仅首次生成，避免触发 pixi 重新解析
    let pixi_path = project_root.join("pixi.toml");
    if !pixi_path.exists() {
        fs::write(&pixi_path, &gen_pixi_toml(&cfg.prefix, &cfg.package))
            .expect("failed to write pixi.toml");
        println!("  wrote pixi.toml");
    }

    // Copy asn1.dll to resources
    if let Ok(exe_path) = std::env::current_exe() {
        if let Some(exe_dir) = exe_path.parent() {
            let dll_name = if cfg!(target_os = "windows") { "asn1.dll" } else { "libasn1.so" };
            let dll_src = exe_dir.join(dll_name);
            if dll_src.exists() {
                let res_dir = src_dir.join("resources");
                fs::create_dir_all(&res_dir).ok();
                fs::copy(&dll_src, res_dir.join(dll_name))
                    .expect("failed to copy asn1.dll");
            }
        }
    }

    // tests/__init__.py
    fs::write(test_dir.join("__init__.py"), "")
        .expect("failed to write tests/__init__.py");

    // Generate _types.py with all type classes
    let mut all_types_code = String::new();
    all_types_code.push_str(&gen_header_comment());
    all_types_code.push_str("# Generated ASN.1 data types\n\n");
    all_types_code.push_str("from dataclasses import dataclass, field\n");
    all_types_code.push_str("from typing import Any\n\n");
    all_types_code.push_str("from ._base import to_json, from_json\n");
    all_types_code.push_str("from ._native import encode, decode_raw\n\n");

    for ti in types {
        let class_code = gen_type_class(ti, types, &cfg.prefix, &cfg.package, cfg, asn_defs);
        all_types_code.push_str(&class_code);
        all_types_code.push('\n');
    }

    fs::write(src_dir.join("_types.py"), &all_types_code)
        .expect("failed to write _types.py");

    // Update __init__.py with type exports
    let mut init_code = gen_init(&cfg.prefix, &cfg.package);
    init_code.push_str(&format!("from ._types import (\n"));
    for ti in types {
        init_code.push_str(&format!("    {pf}{tn},\n", pf = cfg.prefix, tn = ti.name));
    }
    init_code.push_str(")\n\n");
    init_code.push_str("__all__ = [\n");
    for ti in types {
        init_code.push_str(&format!("    \"{pf}{tn}\",\n", pf = cfg.prefix, tn = ti.name));
    }
    init_code.push_str("]\n");
    fs::write(src_dir.join("__init__.py"), &init_code)
        .expect("failed to write __init__.py");

    // Generate test file
    let mut all_tests = String::new();
    all_tests.push_str(&format!("# Auto-generated by {}. Tests\n", super::java::helpers::gen_version()));
    all_tests.push_str("import pytest\n");
    all_tests.push_str(&format!("from cms_data import (\n"));
    for ti in types {
        all_tests.push_str(&format!("    {pf}{tn},\n", pf = cfg.prefix, tn = ti.name));
    }
    all_tests.push_str(")\n\n");
    for ti in types {
        all_tests.push_str(&gen_test(ti, types, &cfg.prefix, &cfg.package));
        all_tests.push('\n');
    }
    fs::write(test_dir.join("test_types.py"), &all_tests)
        .expect("failed to write test_types.py");

    println!("✓ generated Python package in {:?}", project_root);
}
