//! csasn1 — ASN.1 codec library (cdylib)
//!
//! Build output: target/debug/csasn1.dll
//! ffi_auto.rs is auto-generated by build.rs

pub mod ffi_auto;

#[cfg(test)]
#[path = "generated.rs"]
mod generated;

#[cfg(test)]
mod tests {
    // Common imports shared by all test sub-modules.
    // Each sub-module re-exports what it needs from here.
    pub use super::generated::dlt2811_data_types::*;
    pub use rasn::prelude::*;

    mod data_scalars;
    mod data_compound;
    mod complex_types;
    mod jer_god_format;
}
